Programación para *Data Science*
============================

Intro101 - 02.2: Conceptos de Python
--------------------------------------

En este Notebook encontraréis dos conjuntos de ejercicios: un primer conjunto de ejercicios para practicar y que no puntuan, pero que recomendamos intentar resolver y un segundo conjunto que evaluaremos como actividad.


Además, veréis que todas las actividades tienen una etiqueta que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:

* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura. 

* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.

* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span> **Consulta externa independente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recordad que las **etiquetas son informativas**, pero podréis consultar referencias externas en cualquier momento (aunque no se indique explícitamente) o puede ser que podáis hacer una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puedéis consultar referencias externas si queréis, ya sea tanto para ayudaros en la resolución como para ampliar el conocimiento!


---

## Ejercicios y preguntas teóricas para la actividad

A continuación, encontraréis los **ejercicios y preguntas teóricas que debéis completar en esta actividad** y que forman parte de la evaluación de esta unidad.

### Ejercicio 1

Un número primo es aquél que solo es divisible por él mismo y por 1.

a) Escribe un código que compruebe si un número `x = 15` es solo divisible por 1 o por el mismo.  Escribe este código usando un iterador (un `for` o un `while`) que barra todos los valores desde `2` a `x-1`. Crea una variable `divisible`  que tenga por defecto valor `False` y asigne el valor `True` si a lo largo de la iteración encuentra un número natural divisible. Puedes usar el operador modulo `a % b` para saber si un numero `b` es divisible por `a`.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [2]:
# Respuesta
divisible=False
x=15
for i in range(2,x-1):
    if x%i==0: divisible=True

print(divisible)


True



b) Convierte tu código anterior en una función que compruebe si el número del argumento es primo o no, devolviendo True is es primo y False si no es primo. Comprueba tu función con los valores 492366587, 492366585, 48947 y 2,

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [21]:
# Respuesta
def primo(x):
 divisible=True
 i=2
 while i <x and divisible==True:
   if x%i==0: divisible=False
   i+=1

 if x==2 or i==x: print(f"{x} es primo") 
 else: print(f"{x} es divisible por {i}")
 return None
 

primo(492366587)
primo(492366585)
primo(48947)
primo(11)
primo(2)


492366587 es primo
492366585 es divisible por 4
48947 es primo
11 es primo
2 es primo



c) En el cálculo de la función anterior, una vez se ha encontrado un número que es divisible dentro del rango ya no tiene sentido comprobar el resto de números del rango. Por ejemplo si 10 ya es divisble entre 2, ya no hace falta probar de 3 en adelante pues ya sabemos que el número no es primo. 

Modifica la función anterior de la siguiente forma: 
- Una vez se encuentra el divisor, la iteración se interrumpe para no probar el resto de enteros. 
- La función devuelve
    - **Si es primo**: True
    - **Si no es primo**, el primer divisor mayor que 1.
    
Puedes hacer uso del comando *break* dentro de un bucle para interrumpir este, puedes consultar más información sobre break en la documentación de python [aquí](https://docs.python.org/2/tutorial/controlflow.html).

Comprueba tu función con los valores 492366585, 492366587, 48947 y 2,

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [1]:
# Respuesta
#ya hecho en la anterior celda

### Ejercicio 2

La Covid-19 es una enfermedad producida por la infección del virus SARS-CoV-2. La infección es transmisible de persona a persona y su contagiosidad depende de la cantidad del virus en las vías respiratorias. Si cada persona contagiada transmite la enfermedad a $\beta$ contactos en promedio por periodo de tiempo $t$, es posible estimar la evolución del contagio con un modelo matemático sencillo.

Para $ t=1$ día, las transmisiones en España se han estimado a partir de su histórico de las semanas de Febrero y Marzo del 2020 una $\beta = 0.35$ transmisiones por día por infectado.

Durante un periodo de tiempo (por ejempo un día $d$) la tasa de nuevos contagios se puede estimar como  una proporción al número de contagiados del periodo anterior $N$: 

$ \Delta N = N_{1} - N = \beta \cdot N$ (1)

Por tanto, podemos proyectar el número futuro de afectados como 

$ N_{1} = N + \beta \cdot N = (1+\beta) \cdot N$ (2) 

En dos días:

$ N_{2} = (1+\beta) \cdot N_{1} = (1+\beta)^2 \cdot N$  (3)

Y en general en D días tendremos 

$N_{D} = (1+\beta)^D \cdot N$  (4)
 
Asumiendo este sencillo modelo: 

a) Implementa una función de dos parámetros (N: población infectada inicial, D: número de días), que devuelva el cálculo de afectados para D días siguiendo la ecuación (4). Suponiendo una población afectada de 4250 (población afectada en españa a día 13 de Marzo de 2020), usa la función para calcular la población estimada en 1, 2, 7 y 30 días. 

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [19]:
# Respuesta
N=4250
B=0.35
def spread(N,D):
    contagiados=pow(1+B,D)*N
    #print(F"Contagiados en {D} días:",end=" ")
    return contagiados

print(spread(N,0))
print(spread(N,1))
print(spread(N,2))
print(spread(N,7))
print(spread(N,30))


4250.0
5737.5
7745.625000000001
34731.64149433595
34546335.38087164



b) Sabiendo que los Servicios de Medicina Intensiva (SMI) disponen de 3363 camas para enfermos graves, y suponiendo que un 10% de los afectados por el covid-19 requerirán de SMI y una supervivencia del 2,5% (Exitus), escribe un código que calcule:
- El día en curso (Día)
- El total de afectados por el virus para cada día d (Afectados)
- El total de ingresados en SMI por el virus para cada día d (Críticos)
- El total de Exitus por el virus para cada día d (Exitus)
- Si los servicios de SMI no pueden aceptar los ingresados para cada día $d$ (Estado: indicando Saturación/No Saturación)

Imprime en pantalla la información de cada día durante una simulación de tres semanas, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una $\beta = 0.35$ constante. 


<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [25]:
# Respuesta
dias=[0,1,2,7,30]
camas=3363
saturado="No saturación"

for i in dias:
    afectados=int(spread(N,i)) #afectados
    smi=int(spread(N,i)*0.1) #criticos
    exitus=int(afectados*0.025) #2.5% de curados
    if smi>camas: saturado="Saturación"
    print(f"Dia {i}: Afectados: {afectados}. Críticos: {smi}. Éxitus: {exitus}. Estado: {saturado}")
saturado="No saturación"





Dia 0: Afectados: 4250. Críticos: 425. Éxitus: 106. Estado: No saturación
Dia 1: Afectados: 5737. Críticos: 573. Éxitus: 143. Estado: No saturación
Dia 2: Afectados: 7745. Críticos: 774. Éxitus: 193. Estado: No saturación
Dia 7: Afectados: 34731. Críticos: 3473. Éxitus: 868. Estado: Saturación
Dia 30: Afectados: 34546335. Críticos: 3454633. Éxitus: 863658. Estado: Saturación



c) Convierte el código anterior en una función que genere un archivo de texto con nombre `output.txt`, siguiendo este formato: 
```
Dia, Afectados, Críticos, Exitus, Estado
0, 4250, 425,  106, No Saturación
1, 5737, 573,  143, No Saturación
2, 7745, 774,  193, No Saturación
...
```
Con los parámetros de entrada $N$, $D$, $\beta$, camas SMI.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [45]:
# Respuesta

import sys
import os

N=4250
B=0.35
dias=[0,1,2,7,30]
camas=3363
nombre="output.txt"

def inicializar_archivo(nombre):
 file = open(nombre, 'w', encoding='utf-8') #abrir o crear archivo
 file.write("Dia\t| Afectados\t| Críticos\t| Exitus\t| camas SMI\n")
 file = open(nombre, 'r')
 for line in file:
    print(line, end="")

def mostrar_archivo(nombre):
  file = open(nombre, 'r')
  for line in file:
    print(line, end="")

def seguimiento_covid(N,D,B,smi):
    file=open(nombre, 'w', encoding='utf-8')
    saturado="No saturación"
    for i in dias:
     afectados=int(spread(N,i)) #afectados
     smi=int(spread(N,i)*0.1) #criticos
     exitus=int(afectados*0.025) #2.5% de curados
     
     if smi>camas: saturado="Saturación"
     
     file.write(f"{i}\t| {afectados}\t\t| {smi}\t\t| {exitus}\t\t| {saturado}\n")
    saturado="No saturación"


    
inicializar_archivo(nombre)
seguimiento_covid(N,dias,B,smi)
mostrar_archivo(nombre)



Dia	| Afectados	| Críticos	| Exitus	| camas SMI
0	| 4250		| 425		| 106		| No saturación
1	| 5737		| 573		| 143		| No saturación
2	| 7745		| 774		| 193		| No saturación
7	| 34731		| 3473		| 868		| Saturación
30	| 34546335		| 3454633		| 863658		| Saturación


### Ejercicio 3

Dado el siguiente diccionario:

In [ ]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

Escribid una función que pregunte al usuario que introduzca el nombre de una persona y muestre por pantalla el nombre de la persona y su teléfono. 

Tened en cuenta que:

- La función debe controlar que el valor introducido por el usuario es un nombre que existe en el diccionario. En caso contrario, mostrará un mensaje de error (

) y devolverá el valor False.
- Debéis tener en cuenta que el nombre de las personas que nos pasan por parámetro puede ser en minúsculas, mayúsculas o una combinación de ambas, y que debemos encontrar el número de teléfono aunque la capitalización de la cadena entrada por el usuario no sea exactamente la misma que hemos almacenado en el diccionario.
- Suponed que  no hay acentos en los nombres.

Nota 1: Para realizar la actividad, tendréis que capturar un texto que entrará el usuario. Consultad la [documentación oficial de la función input](https://docs.python.org/3/library/functions.html#input) para ver cómo hacerlo.

Nota 2: También tendréis que pensar cómo tratar el hecho de que el usuario pueda utilizar mayúsculas y minúsculas en la escritura del nombre en el diccionario. ¡Os animamos a usar un buscador para intentar encontrar alguna alternativa para resolver este subproblema! ¡Recordad citar las referencias que hayáis usado para resolverlo!

<span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [61]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

# Respuesta
def agenda():
    nombre=input("¿Nombre?").capitalize()
    print(f"{nombre}, ",end="")
    if nombre in d:
        print(f"Teléfono: {d[nombre]}")
    else: print("El nombre introducido no corresponde a ninguna persona")

agenda()


Alex, Teléfono: 344334443


Referencias consultadas:

https://docs.python.org/3/library/stdtypes.html?highlight=string%20capitalize#string-methods

###  Ejercicio 4

Python dispone de un **idiom** muy útil conocido como `list comprehension`. Utilizando este **idiom**, proporcionad una expresión que devuelva las listas siguientes.

Nota: Para realizar esta actividad necesitaréis investigar qué son las `list comprehension` y qué sintaxis utilizan. Para ello, se recomienda en primer lugar que utilicéis un buscador para encontrar información genérica sobre esta construcción. Después, os recomendamos que consultéis stackoverflow para ver algunos ejemplos de problemas que se pueden resolver con esta construcción.


[stackoverflow](https://stackoverflow.com/) es un sitio de preguntas-y-respuestas muy popular entre programadores. Veréis que para la gran mayoría de las dudas que tengáis, habrá alguien que ya les habrá tenido (y consultado) anteriormente! Así pues, más allá de preguntar vosotros mismos las dudas allí (nosotros ya tenemos el foro del aula para ello!), consultar esta web os permitirá ver qué soluciones proponen otros programadores a estas dudas. A menudo habrá más de una solución a un mismo problema, y podréis valorar cuál es la más adecuada para vuestro problema.

Para ver ejemplos de problemas que son adecuados para resolver con **list comprehensions**, os recomendamos leer las siguientes páginas:
* https://stackoverflow.com/questions/12555443/squaring-all-elements-in-a-list
* https://stackoverflow.com/questions/18551458/how-to-frame-two-for-loops-in-list-comprehension-python
* https://stackoverflow.com/questions/24442091/list-comprehension-with-condition
* https://stackoverflow.com/questions/41676212/i-want-to-return-only-the-odd-numbers-in-a-list
* https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension

<span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>


a) Una lista con los valores $4 x^2$ donde $x$ es cada uno de los números de la lista `list_1`:

In [65]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

lista=[(4*x)**2 for x in list_1]

print(lista)

# Respuesta


[16, 64, 144, 256, 400, 576, 784, 1024, 1296]


b) Una lista con los valores $x/(x+1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [70]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta

lista=[round(x/(x+1),2) for x in list_1]
print(lista)

[0.5, 0.67, 0.75, 0.8, 0.83, 0.86, 0.88, 0.89, 0.9]


c) Una lista con los valores $4x^2/(4x^2-1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [75]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta
lista=[round(((4*x**2)/((4*x**2)-1)),2) for x in list_1]
print(lista)


[1.33, 1.07, 1.03, 1.02, 1.01, 1.01, 1.01, 1.0, 1.0]


In [76]:

x = lambda a : a + 10
print(x(5))

15


### Ejercicio 5

Las funciones `lambda` son formas de expresar y definir funciones pequeñas sin necesidad de usar el constructor `def funcion():`.

Lee sobre las funciones lambda, por ejemplo [aquí](https://www.w3schools.com/python/python_lambda.asp) o [aquí](https://realpython.com/python-lambda/)

Escribe una función $f$ con argumento $n$, $f(n)$, que **devuelva una función** lambda, que esta a su vez devuelva $n$ copias de una cadena de caracteres en su argumento: 

<span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [79]:
# Respuesta

def f(n): 
   return lambda r: r*n # Definir de la función usando una método lambda
    
r = f(5)
r("Hola")  # Donde deberíamos ver 5 copias del literal "Hola "

'HolaHolaHolaHolaHola'

### Ejercicio Opcional

Existe una expresión atribuida a John Wallis (1616) para la estimación del valor de $\pi$, consistente en: 

$$
\frac{\pi}{2} = \prod_{n=1}^{N} (\frac{4n^2}{4n^2 - 1})
$$
si $N$ es suficientemente grande  $N \to \infty$. 

Escribe una función que, dado una aproximación N, calcule una estimación de $\pi$ siguiendo la fórmula de Wallis. 



**Consideraciones:**

- Investigad las funciones map, reduce
- También podéis usar una list comprehension
- Las funciones lambda os pueden ser útiles

<span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [22]:
# Respuesta
from functools import reduce

N=100000000

p1=list(map(lambda x: ((4*x**2)/((4*x**2)-1)),range(1,N)))
p3=reduce(lambda x,y: x*y, p1)
print(p3*2)



3.141592643066262
